### ISSUE TITLE
demo stuck on "" with fan running full speed

### ISSUE THREAD

**Issue by Tetsujinfr** [NVIDIA-AI-IOT/jetson-cloudnative-demo#1]
hi 

I have followed the install steps and launched the demo. I click enter after the first echo  prompt and I got stuck on the terminal with message "Launching DeepStream Container".
No error message, no further echo, nothing, just the fan running full steam. After 5 min I just rebooted my Xavier NX devkit.
I have a 500 M2 SSD, did setup the swap file to 32G as instructed. My docker data are under /media/username/SSD folder.

Now I do not have a USB headset with microphone but I was willing to run the demo anyway. Could that be the reason?

thanks for your help.

**Comment by idavis** [comment]
Have you checked to see if it is downloading the container images? They can take quite a while to download if you don't have them already.

**Comment by Tetsujinfr** [comment]
I think I am good with the docker data, I retrieved them all and then transferred the content on my M.2 drive under a "docker folder" (/media/username/SSD/docker)
Here is the docker folder properties:
![docker_files](https://user-images.githubusercontent.com/29961693/83696082-6d715000-a5f3-11ea-9a2b-82fcf059e698.png)

Could the demo take more than 2 or 3 minutes to load?  I killed it after 5 min but not sure if I should try longer.
I I want to investigate, is there a log file somwhere or do I need to add my own debugging tags to track where this issue is exactly?

**Comment by idavis** [comment]
The scripts hide the docker pull commands. The demo takes 3 minutes for me with "MODE 15W 6CORE" and all images fully downloaded. I think it took over 20 minutes the first time and I'm running a 970 Pro NVMe.

**Comment by Tetsujinfr** [comment]
Ok so I got the demo working fine, quite impressive and running pretty fast vs other deepnet model inferences not as optimized.

So I think there is a slight glitch in the readme instructions, where it says:
`sudo ln -s /home/nvidia/nvme/docker /var/lib/docker`
I think it should say:
`sudo ln -s /home/nvidia/nvme/docker /var/lib/`

So basically my symlink for the SSD docker data was not where the code was expecting it to be I think. I had to move my already existing /var/lib/docker folder (with root privilege), then execute `sudo ln -s /yourM2SSDpath/docker /var/lib/` to create the proper shortcut.
Let me know if I am missing something here, otherwise pls tweak/clarify the readme please for others.

thanks for your replies and for the superb demo.
