### ISSUE TITLE
More information on containers

### ISSUE THREAD

**Issue by ysiegel29** [NVIDIA-AI-IOT/jetson-cloudnative-demo#3]
Hello,
This demo is impressive and I would like to better understand whether I should  base my project on containers?
Can someone kindly direct me to ressources on this topic?
Also the container provided by nvidia are for demo purpose only right? They can’t be tailored to a specific project.
Thank you!

**Comment by jaybdub** [comment]
Hi ysiegel29,

Thanks for reaching out!

Using containers may be a good way to package your application.

@suhash-gitlab has a webinar hosted here which covers this topic

https://developer.nvidia.com/gtc/2020/video/s22707-vid

I also recommend checking out the following NGC containers as a starting point for your projects.

*  https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base

* https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch

The second container is the base for the pose and gaze containers in this project.  You could extend these for your application in a similar way.

Please let me know if this helps or you run into any issues.

Best,
John

**Comment by ysiegel29** [comment]
Thanks, Will check this out.
Thanks
